// Title: Convert schema with languages
// Usage: npm run language-import
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const listPath = 'ext/github/linguist/lib/linguist/languages.yml';
const schemaPath = 'schema/language.linguist.json'
const list = yaml.safeLoad(fs.readFileSync(listPath));
const template = 
{
    "id": "https://repometric.github.io/linterhub/schema/language.linguist.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This schema describes programming languages and extensions",
    "description": "The autogenerated list of programming languages and extensions from linguist project",
    "oneOf": [
        { "$ref": "#/definitions/language" }
    ],
    "definitions": {
        "language": {
            "type": "string",
            "description": "The programming language name",
            "oneOf": [
            ]
        }
    }
};
template.definitions.language.oneOf = Object.keys(list).map(name =>
{
    let item = list[name];
    let language =
    {
        "enum": [name]
    };
    if (item.extensions && item.extensions.length) language.extensions = item.extensions;
    if (item.filenames && item.filenames.length) language.filenames = item.filenames;
    return language;
});
const formatted = JSON.stringify(template, null, 4);
fs.writeFileSync(schemaPath, formatted + '\n');
console.log(`Done! Total ${template.definitions.language.oneOf.length} languages.`);
