// Title: Convert schema with licenses
// Usage: npm run license-import
const fs = require('fs');
const path = require('path');
const listPath = 'ext/spdx/license-list-data/json/licenses.json';
const schemaPath = 'schema/license.json'
const list = JSON.parse(fs.readFileSync(listPath));
const template = 
{
    "id": "https://repometric.github.io/linterhub/schema/license.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This schema describes the engine license",
    "description": "The autogenerated name of SPDX license",
    "type": "string",
    "enum": [
    ],
    "additionalItems": false
};
template.enum = list.licenses.map(l => l.licenseId);
const formatted = JSON.stringify(template, null, 4);
fs.writeFileSync(schemaPath, formatted + '\n');
console.log(`Done! Total ${template.enum.length} licenses.`);
